version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    networks:
      - default
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
        MYSQL_DATABASE: bookend-authorization-service
        MYSQL_ROOT_PASSWORD: 1234
    networks:
      - default

  author-service:
    build: /Coding/java-oxygen/Workspace/bookend-services/author-service.
    depends_on:
      - mongo
    container_name: ascon
    ports:
      - 8085:8085
    networks:
      - default
  book-service:
    build: /Coding/java-oxygen/Workspace/bookend-services/book-service.
    depends_on:
      - mongo
    container_name: bscon
    ports:
      - 8082:8082
    networks:
      - default

  authorization-service:
    build: /Coding/java-oxygen/Workspace/bookend-services/authorization-server.
    depends_on:
      - mysqldb
    container_name: authscon
    ports:
      - 9191:9191
    networks:
      - default
  
networks:
  default:
    external: true
    name: bookendnet