version: "3"
services:
  authorization-service:
    build: /authorization-server.
    depends_on:
      - mysqlcon
    container_name: authscon
    ports:
      - 9191:9191
    networks:
      - default
  author-service:
    build: /author-service.
    depends_on:
      - mongo
    container_name: ascon
    ports:
      - 8085:8085
    networks:
      - default
  book-service:
    build: /book-service.
    depends_on:
      - mongo
    container_name: bscon
    ports:
      - 8082:8082
    networks:
      - default
  book-club-service:
    build: /book-club-service.
    depends_on:
      - mysqlcon
    container_name: bclubcon
    ports:
      - 8089:8089
    networks:
      - default

  mail-service:
    build: /mail-service.
    depends_on:
      - mysqlcon
    container_name: mail-ser-con
    ports:
      - 8090:8090
    networks:
      - default
  message-service:
    build: /message-service.
    depends_on:
      - mongo
    container_name: message-ser-con
    ports:
      - 8087:8087
    networks:
      - default

  
networks:
  default:
    external: true
    name: bookendnet