server:
  port: 8083
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookend-shelfservice?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token

    client:
      client-id: mobile
      client-secret: pin