server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mail-service?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: smtp.gmail.com
    username: gradd.sschool@gmail.com
    password: vxnqvcuubokizitj
    port: 587
    properties.mail.smtp:
      auth: true
      socketFactory:
        port: 465
        class: javax.net.ssl.SSLSocketFactory
        fallback: false



