version: "3"
services:
  book-club-service:
    build: .
    container_name: book-club-container
    ports:
      - 8089:8089
    networks:
      - default

networks:
  default:
    external: true
    name: bookendnet