server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookend-authorization-service?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey
    username: root
    password: group10
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace