server:
  port: 8082
spring:
  datasource:

    url: jdbc:h2:file:~/data/demo_db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

      properties:
        hibernate:

          dialect: org.hibernate.dialect.H2Dialect
    kafka:
      producer:
        properties:
          spring:
            json:
              add:
                type:
                  headedrs: false
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token

    client:
      client-id: mobile
      client-secret: pin