version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    networks:
      - default

  author-service:
    build: .
    depends_on:
      - mongo
    container_name: ascon
    ports:
      - 8085:8085
    networks:
      - default

networks:
  default:
    external: true
    name: bookendnet