
server:
  port: 8082
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: book-com.bookclupservice.bookclubservice.service
  datasource:
    kafka:
      producer:
        properties:
          spring:
            json:
              add:
                type:
                  headedrs: false
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token

    client:
      client-id: mobile
      client-secret: pin