version: "3"
services:
  authorization-service:
    build: .
    container_name: authscon
    ports:
      - 9191:9191
    networks:
      - default

networks:
  default:
    external: true
    name: bookendnet